- id: '1703623708618'
  alias: Leak Detection & Notifier
  description: ''
  use_blueprint:
    path: tteggelit/leak-detector-notifier.yaml
    input:
      notify_device: c649c07764020e9d99e38656cf640e62
