substitutions:
  name: guest-bedroom-light-left
  friendly_name: Left Guest Bedroom Light

packages:
  Kauf.RGBWW: github://KaufHA/kauf-rgbww-bulbs/kauf-bulb.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
api:
  encryption:
    key: BN89UGbQvj9xZaqASMu6Me9HnNYFQZEWPojQuvapXJ0=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
