substitutions:
  name: guest-bedroom-light-right
  friendly_name: Right Guest Bedroom Light
  sub_max_power: '1.0'
  light_restore_mode: RESTORE_AND_ON

packages:
  Kauf.RGBWW: github://KaufHA/kauf-rgbww-bulbs/kauf-bulb.yaml
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
api:
  encryption:
    key: a1Q4bdmV2Gu5/pH82wN/amtekZR459Jhwhpux9XmJkU=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
