blueprint:
  name: Leak detection & notifier
  description: Send a notification when any configured moisture sensor becomes moist
  domain: automation
  input:
    notify_device:
      name: Notify device
      description: The device where the notification should be sent to.
      selector:
        device:
          integration: mobile_app
          multiple: false
  source_url: https://gist.github.com/tteggelit/49d33234078fe0594be62234e07bffef
trigger:
- event_data: {}
  event_type: state_changed
  platform: event
condition:
- condition: template
  value_template: '{{ trigger.event.data.new_state.attributes.device_class == "moisture"
    }}'
- condition: template
  value_template: '{{ trigger.event.data.new_state.state == "on" }}'
action:
  domain: mobile_app
  type: notify
  device_id: !input notify_device
  message: '{{ trigger.event.data.new_state.attributes.friendly_name }} has detected
    a leak.'
  title: Leak detected!
  data:
    push:
      sound:
        name: default
        critical: 1
        volume: 1.0
mode: single
