automation:
  - alias: 'Thunderstorm Alert'
    description: >-
      Sends tiered alerts for approaching lightning, but only if the NWS
      forecast also shows a >50% chance of thunderstorms.
    trigger:
      # This trigger will fire if lightning is detected near any of your monitored locations.
      # Trigger IDs are added for clarity in the 'action' section.
      - platform: numeric_state
        entity_id: sensor.des_moines_lightning_distance
        below: 120
        id: 'des_moines'
      - platform: numeric_state
        entity_id: sensor.quad_cities_lightning_distance
        below: 80
        id: 'quad_cities'
      - platform: numeric_state
        entity_id: sensor.dixon_lightning_distance
        below: 40
        id: 'dixon'
      - platform: numeric_state
        entity_id: sensor.home_lightning_distance
        below: 25
        id: 'oswego'
    condition:
      # This condition checks the NWS forecast. The action below will only run if
      # there is a >50% chance of thunderstorms in the next 4 hours.
      - condition: template
        value_template: >-
          {% set weather_entity = 'weather.klot' %}
          {% set forecast = state_attr(weather_entity, 'forecast') %}
          {% set hours_to_check = 4 %}
          {% set threshold = 50 %}
          {% set storm_predicted = namespace(value=false) %}
  
          {% if forecast %}
            {% for i in range(hours_to_check) %}
              {% if forecast[i] %}
                {% set period = forecast[i] %}
                {% set precip_chance = period.precipitation_probability | int(0) %}
                {% set detailed_desc = period.detailed_description | lower %}
                {% if precip_chance > threshold and 'thunderstorm' in detailed_desc %}
                  {% set storm_predicted.value = true %}
                {% endif %}
              {% endif %}
            {% endfor %}
          {% endif %}
  
          {{ storm_predicted.value }}
    action:
      - choose:
          # Case 1: Lightning near Des Moines, IA
          - conditions:
              - condition: trigger
                id: 'des_moines'
            sequence:
              - action: notify.mobile_app_tis_iphone
                metadata: {}
                data:
                  title: "Distant Storm Warning (Des Moines)"
                  message: "Confirmed storm w/ lightning near Des Moines, moving east. Estimated arrival in 4-6 hours. Time for meds!"
                  data:
                    push: 
                      sound:
                        name: default
                        critical: 1
                        volume: 1
          # Case 2: Lightning near the Quad Cities
          - conditions:
              - condition: trigger
                id: 'quad_cities'
            sequence:
              - action: notify.mobile_app_tis_iphone
                metadata: {}
                data:
                  title: "Approaching Storm (Quad Cities)"
                  message: "Confirmed storm w/ lightning over the Quad Cities, headed your way. Estimated arrival in 2-3 hours."
                  data:
                    push: 
                      sound:
                        name: default
                        critical: 1
                        volume: 1
          # Case 3: Lightning near Dixon, IL
          - conditions:
              - condition: trigger
                id: 'dixon'
            sequence:
              - action: notify.mobile_app_tis_iphone
                metadata: {}
                data:
                  title: "Nearby Storm (Dixon)"
                  message: "Confirmed storm w/ lightning near Dixon. Estimated arrival in about 1 hour."
                  data:
                    push: 
                      sound:
                        name: default
                        critical: 1
                        volume: 1
          # Case 4: Lightning near you in Oswego
          - conditions:
              - condition: trigger
                id: 'oswego'
            sequence:
              - action: notify.mobile_app_tis_iphone
                metadata: {}
                data:
                  title: "⚡ Thunderstorm Starting!"
                  message: "Lightning detected within 25 km. The storm is here."
        default: []
    mode: parallel
    max: 10
  
  
