automation:
  - alias: 'Thunderstorm Alert'
    description: >-
      Sends tiered alerts for approaching lightning, but only if the forecast
      shows a >50% chance of thunderstorms in the next 4 hours.
    trigger:
      - platform: numeric_state
        entity_id: sensor.des_moines_lightning_distance
        below: 120
        id: 'des_moines'
      - platform: numeric_state
        entity_id: sensor.quad_cities_lightning_distance
        below: 80
        id: 'quad_cities'
      - platform: numeric_state
        entity_id: sensor.dixon_lightning_distance
        below: 40
        id: 'dixon'
      - platform: numeric_state
        entity_id: sensor.home_lightning_distance
        below: 25
        id: 'oswego'
    action:
      # Step 1: Get the forecast
      - service: weather.get_forecasts
        target:
          entity_id: weather.openweathermap
        data:
          type: hourly
        response_variable: weather_response

      # Step 2: Check if thunderstorm is likely
      - variables:
          forecast: "{{ weather_response['forecast'] }}"
          storm_predicted: >
            {% set forecasted = false %}
            {% for period in forecast[:4] %}
              {% set precip_prob = (period.precipitation_probability | int(0)) %}
              {% set condition = (period.condition | lower) %}
              {% if precip_prob > 50 and ('thunder' in condition or 'storm' in condition or 'tstorm' in condition) %}
                {% set forecasted = true %}
              {% endif %}
            {% endfor %}
            {{ forecasted }}

      # Step 3: Only send alert if storm is predicted
      - choose:
          - conditions: "{{ trigger.id == 'des_moines' }}"
            sequence:
              - choose:
                  - conditions: "{{ storm_predicted }}"
                    sequence:
                      - service: notify.mobile_app_tis_iphone
                        data:
                          title: "Distant Storm Warning (Des Moines)"
                          message: "Confirmed storm w/ lightning near Des Moines, moving east. Estimated arrival in 4-6 hours. Time for meds!"
                          data:
                            push:
                              sound:
                                name: default
                                critical: 1
                                volume: 1

          - conditions: "{{ trigger.id == 'quad_cities' }}"
            sequence:
              - choose:
                  - conditions: "{{ storm_predicted }}"
                    sequence:
                      - service: notify.mobile_app_tis_iphone
                        data:
                          title: "Approaching Storm (Quad Cities)"
                          message: "Confirmed storm w/ lightning over the Quad Cities, headed your way. Estimated arrival in 2-3 hours."
                          data:
                            push:
                              sound:
                                name: default
                                critical: 1
                                volume: 1

          - conditions: "{{ trigger.id == 'dixon' }}"
            sequence:
              - choose:
                  - conditions: "{{ storm_predicted }}"
                    sequence:
                      - service: notify.mobile_app_tis_iphone
                        data:
                          title: "Nearby Storm (Dixon)"
                          message: "Confirmed storm w/ lightning near Dixon. Estimated arrival in about 1 hour."
                          data:
                            push:
                              sound:
                                name: default
                                critical: 1
                                volume: 1

          - conditions: "{{ trigger.id == 'oswego' }}"
            sequence:
              - service: notify.mobile_app_tis_iphone
                data:
                  title: "⚡ Thunderstorm Starting!"
                  message: "Lightning detected within 25 km. The storm is here."
                  data:
                    push:
                      sound:
                        name: default
                        critical: 1
                        volume: 1
    mode: single
