# This package consists of an automation to process the button events.
# Here are how the button events are processed:
# Push Up           - Turn light on
# Push Down         - Turn lights off
# Hold Up           - Turn up the brightness to a max of 100%
# Hold Down         - Turn down the brightness to a min of 3%
#
# You will need to update the automation to reference the right device_id of the
# remote and what lights you want to control.
#

# Automations
automation:
  - alias: Playroom Cabinet Lights Control
    description: Control lights with IKEA Bilresa remote
    mode: restart
    triggers:
      - trigger: mqtt
        topic: "zigbee2mqtt/Playroom Cabinet Lights Remote/action"
        payload: "on"
        id: button_on
      - trigger: mqtt
        topic: "zigbee2mqtt/Playroom Cabinet Lights Remote/action"
        payload: "off"
        id: button_off
      - trigger: mqtt
        topic: "zigbee2mqtt/Playroom Cabinet Lights Remote/action"
        payload: "brightness_move_up"
        id: brightness_up
      - trigger: mqtt
        topic: "zigbee2mqtt/Playroom Cabinet Lights Remote/action"
        payload: "brightness_move_down"
        id: brightness_down
      - trigger: mqtt
        topic: "zigbee2mqtt/Playroom Cabinet Lights Remote/action"
        payload: "brightness_stop"
        id: brightness_stop
    actions:
      - choose:
          # Turn on light
          - conditions:
              - condition: trigger
                id: button_on
            sequence:
              - action: light.turn_on
                target:
                  entity_id:
                    - light.playroom_cabinet_lights
                data:
                  brightness_pct: 100

          # Turn off light
          - conditions:
              - condition: trigger
                id: button_off
            sequence:
              - action: light.turn_off
                target:
                  entity_id:
                    - light.playroom_cabinet_lights

          # Brightness up (hold top button)
          - conditions:
              - condition: trigger
                id: brightness_up
            sequence:
              - repeat:
                  while:
                    - condition: template
                      value_template: >
                        {{ state_attr('light.playroom_cabinet_lights', 'brightness') | int(0) < 255 }}
                  sequence:
                    - action: light.turn_on
                      target:
                        entity_id:
                          - light.playroom_cabinet_lights
                      data:
                        brightness_step_pct: 10
                    - delay:
                        milliseconds: 200

          # Brightness down (hold bottom button)
          - conditions:
              - condition: trigger
                id: brightness_down
            sequence:
              - repeat:
                  while:
                    - condition: template
                      value_template: >
                        {{ state_attr('light.playroom_cabinet_lights', 'brightness') | int(0) > 23 }}
                  sequence:
                    - action: light.turn_on
                      target:
                        entity_id:
                          - light.playroom_cabinet_lights
                      data:
                        brightness_step_pct: -10
                    - delay:
                        milliseconds: 200
              - action: light.turn_on
                target:
                  entity_id:
                    - light.playroom_cabinet_lights
                data:
                  brightness_pct: 3
  - alias: Turn On Playroom Cabinet Lights When A Door Opens
    description: ''
    triggers:
    - trigger: door.opened
      target:
        entity_id:
        - binary_sensor.left_playroom_cabinet_door_sensor_contact
        - binary_sensor.middle_playroom_cabinet_door_sensor_contact
        - binary_sensor.right_playroom_cabinet_door_sensor_contact
      options:
        for: 00:00:00
        behavior: first
    conditions: []
    actions:
    - action: light.turn_on
      metadata: {}
      target:
        entity_id: light.playroom_cabinet_lights
      data:
        transition: 2
        brightness_pct: 100
    mode: single
  - alias: Turn Off Playroom Cabinet Lights When All Doors Close
    description: ''
    triggers:
    - trigger: door.closed
      target:
        entity_id:
        - binary_sensor.left_playroom_cabinet_door_sensor_contact
        - binary_sensor.middle_playroom_cabinet_door_sensor_contact
        - binary_sensor.right_playroom_cabinet_door_sensor_contact
      options:
        for:
          hours: 0
          minutes: 0
          seconds: 30
        behavior: all
    conditions: []
    actions:
    - action: light.turn_off
      metadata: {}
      target:
        entity_id: light.playroom_cabinet_lights
      data:
        transition: 3
    mode: single
