# This package consists of an automation to process the button events.
# Here are how the button events are processed:
# Push Up           - Turn light on
# Push Down         - Turn lights off
# Hold Up           - Turn up the brightness to a max of 100%
# Hold Down         - Turn down the brightness to a min of 3%
#
# You will need to update the automation to reference the right device_id of the
# remote and what lights you want to control.
#

# Automations
automation:
  - alias: PLayroom Cabinet Lights Control
    description: Control lightis with Bilresa remote
    mode: restart
    trigger:
      - platform: mqtt
        topic: "zigbee2mqtt/Playroom Cabinet Lights Remote/action"
        payload: "on"
        id: button_on
      - platform: mqtt
        topic: "zigbee2mqtt/Playroom Cabinet Lights Remote/action"
        payload: "off"
        id: button_off
      - platform: mqtt
        topic: "zigbee2mqtt/Playroom Cabinet Lights Remote/action"
        payload: "brightness_move_up"
        id: brightness_up
      - platform: mqtt
        topic: "zigbee2mqtt/Playroom Cabinet Lights Remote/action"
        payload: "brightness_move_down"
        id: brightness_down
      - platform: mqtt
        topic: "zigbee2mqtt/Playroom Cabinet Lights Remote/action"
        payload: "brightness_stop"
        id: brightness_stop
    action:
      - choose:
          # Turn on light
          - conditions:
              - condition: trigger
                id: button_on
            sequence:
              - service: light.turn_on
                target:
                  entity_id:
                    - light.playroom_cabinet_lights
                data:
                  brightness_pct: 100
          
          # Turn off light
          - conditions:
              - condition: trigger
                id: button_off
            sequence:
              - service: light.turn_off
                target:
                  entity_id:
                    - light.playroom_cabinet_lights
          
          # Brightness up (hold top button)
          - conditions:
              - condition: trigger
                id: brightness_up
            sequence:
              - repeat:
                  while:
                    - condition: template
                      value_template: >
                        {{ state_attr('light.playroom_cabinet_lights', 'brightness') | int(0) < 255 }}
                  sequence:
                    - service: light.turn_on
                      target:
                        entity_id:
                          - light.playroom_cabinet_lights
                      data:
                        brightness_step_pct: 10
                    - delay:
                        milliseconds: 200
          
          # Brightness down (hold bottom button)
          - conditions:
              - condition: trigger
                id: brightness_down
            sequence:
              - repeat:
                  while:
                    - condition: template
                      value_template: >
                        {{ state_attr('light.playroom_cabinet_lights', 'brightness') | int(0) > 23 }}
                  sequence:
                    - service: light.turn_on
                      target:
                        entity_id:
                          - light.playroom_cabinet_lights
                      data:
                        brightness_step_pct: -10
                    - delay:
                        milliseconds: 200
              - service: light.turn_on
                target:
                  entity_id:
                    - light.playroom_cabinet_lights
                data:
                  brightness_pct: 3
